### ISSUE TITLE
sra_search runs even with 0 query signatures

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sra_search#4]
when we mess up the query signatures we get this message:
```
[2022-09-22T15:37:10Z INFO  sra_search] Loaded 0 query signatures
```
and then
```
[2022-09-22T15:37:10Z INFO  sra_search] Loading siglist
[2022-09-22T15:37:10Z INFO  sra_search] Loaded 5000 sig paths in siglist
[2022-09-22T15:37:10Z INFO  sra_search] Processed 0 search sigs
[2022-09-22T15:38:23Z INFO  sra_search] Processed 1000 search sigs
[2022-09-22T15:39:58Z INFO  sra_search] Processed 2000 search sigs
```

it seems like it would be good to error-exit when no query signatures are loaded :)

**Comment by ccbaumler** [comment]
This was a result of a `scaled` value mismatch. The query signature was `scaled` at 2000 while the signatures searched were `scaled` at 1000. This was verified by manually overriding the `scaled` value. 

See #2

A possible starting point for this issue could be at [this `error` message in the `main.rs` file](https://github.com/sourmash-bio/sra_search/blob/617f246f65644e71569c155b44796e9adfaaac18/searcher/src/main.rs#L116)

**Comment by ctb** [comment]
I think there are two separate problems -

first, `sra_search` runs even when there are no query signatures. (this issue)

second, `sra_search` silently fails to load query signatures that are not at the precise scaled specified by `--scaled`, which defaults to 1000 (https://github.com/sourmash-bio/sra_search/issues/2)

and now third, `sra_search` loudly fails to load subject signatures at the wrong scaled value even when it could just downsample them - see https://github.com/sourmash-bio/sra_search/issues/6.
